import { createHash } from 'node:crypto';
import fs from 'node:fs/promises';

import { processingError } from './errors.mjs';

const controlKeys = new Set([
    'SourceFile',
    'ExifTool:ExifToolVersion',
    'errors',
    'warnings'
]);

// This is deliberately an exact allowlist for the fixed, lossy WebP profile
// generated by the pinned photo pipeline. A new encoder field, colour profile,
// EXIF/XMP chunk, comment, or other unreviewed tag therefore fails closed.
const allowedPublicWebpTechnicalKeys = new Set([
    'Composite:ImageSize',
    'Composite:Megapixels',
    'File:FileType',
    'File:FileTypeExtension',
    'File:MIMEType',
    'File:System:Directory',
    'File:System:FileAccessDate',
    'File:System:FileCreateDate',
    'File:System:FileInodeChangeDate',
    'File:System:FileModifyDate',
    'File:System:FileName',
    'File:System:FilePermissions',
    'File:System:FileSize',
    'RIFF:HorizontalScale',
    'RIFF:ImageHeight',
    'RIFF:ImageWidth',
    'RIFF:VP8Version',
    'RIFF:VerticalScale'
]);

const maximumRawKeys = 1_100;
const exiftoolReadArguments = Object.freeze([
    '-G0:1',
    '-a',
    '-s',
    '-n',
    '-struct',
    '-all:all'
]);

export function sha256Hex(bytes) {
    if (!ArrayBuffer.isView(bytes) && !(bytes instanceof ArrayBuffer)) {
        throw processingError('invalid-request');
    }

    return createHash('sha256').update(Buffer.from(
        bytes instanceof ArrayBuffer
            ? new Uint8Array(bytes)
            : new Uint8Array(bytes.buffer, bytes.byteOffset, bytes.byteLength)
    )).digest('hex');
}

export async function scanPhotoMetadata({
    exiftool,
    filePath,
    bytes,
    scannerVersion,
    stage,
    expectedFormat,
    expectedDimensions = null,
    policy
}) {
    if (
        !exiftool ||
        typeof exiftool.readRaw !== 'function' ||
        typeof filePath !== 'string' ||
        !policy ||
        !(
            (stage === 'source' && ['jpeg', 'png'].includes(expectedFormat)) ||
            (
                stage === 'public-derivative' &&
                expectedFormat === 'webp' &&
                validDimensions(expectedDimensions)
            )
        )
    ) {
        throw processingError('invalid-request');
    }

    const expectedSubject = {
        sha256: sha256Hex(bytes),
        byteLength: bytes.byteLength
    };
    await assertFileMatchesSubject(filePath, expectedSubject);

    let raw;
    try {
        raw = await exiftool.readRaw(filePath, [...exiftoolReadArguments]);
    } catch {
        throw processingError('metadata-scan-failed');
    }

    await assertFileMatchesSubject(filePath, expectedSubject);

    if (!isPlainObject(raw)) {
        throw processingError('metadata-scan-failed');
    }

    const rawKeys = Object.keys(raw);
    if (
        rawKeys.length > maximumRawKeys ||
        !Array.isArray(raw.errors) || raw.errors.length !== 0 ||
        !Array.isArray(raw.warnings) || raw.warnings.length !== 0 ||
        !hasRequiredTechnicalBaseline(raw, scannerVersion, expectedFormat, expectedDimensions)
    ) {
        throw processingError('metadata-scan-failed');
    }

    const metadataPaths = rawKeys
        .filter(key => !controlKeys.has(key))
        .filter(key => stage !== 'public-derivative' || !allowedPublicWebpTechnicalKeys.has(key))
        .sort();

    if (
        metadataPaths.length > 1_000 ||
        metadataPaths.some(path => !isSafeMetadataPath(path))
    ) {
        throw processingError('metadata-scan-failed');
    }

    const result = {
        schemaVersion: policy.schemaVersion,
        mediaType: 'photo',
        metadata: metadataPaths.map(path => ({
            path: path.replaceAll(':', '.'),
            value: true
        })),
        chapters: []
    };
    const subject = expectedSubject;
    const envelope = {
        schemaVersion: policy.schemaVersion,
        resultKind: 'metadata',
        subject,
        scanner: {
            name: 'exiftool',
            version: scannerVersion
        },
        status: {
            completed: true,
            truncated: false,
            exitCode: 0
        },
        result
    };
    const integrityAssessment = policy.assessScanEnvelope(envelope, {
        ...subject,
        scannerName: 'exiftool',
        scannerVersion,
        resultKind: 'metadata'
    });
    const metadataAssessment = policy.assessMetadataProbe(
        result,
        stage === 'source' ? policy.stages.source : policy.stages.publicDerivative
    );

    if (!integrityAssessment.valid || !metadataAssessment.probeValid) {
        throw processingError('metadata-scan-failed');
    }
    if (stage === 'public-derivative' && !metadataAssessment.valid) {
        throw processingError('derivative-rejected');
    }

    return Object.freeze({
        sha256: subject.sha256,
        byteLength: subject.byteLength,
        scannerName: 'exiftool',
        scannerVersion,
        metadataEntryCount: result.metadata.length,
        findingCategories: Object.freeze(
            metadataAssessment.findings.map(finding => finding.category).sort()
        )
    });
}

async function assertFileMatchesSubject(filePath, expectedSubject) {
    let fileBytes;
    try {
        fileBytes = await fs.readFile(filePath);
    } catch {
        throw processingError('metadata-scan-failed');
    }

    if (
        fileBytes.byteLength !== expectedSubject.byteLength ||
        sha256Hex(fileBytes) !== expectedSubject.sha256
    ) {
        throw processingError('metadata-scan-failed');
    }
}

function hasRequiredTechnicalBaseline(raw, scannerVersion, expectedFormat, expectedDimensions) {
    const expected = {
        jpeg: { fileType: 'JPEG', extension: 'JPG', mimeType: 'image/jpeg' },
        png: { fileType: 'PNG', extension: 'PNG', mimeType: 'image/png' },
        webp: { fileType: 'WEBP', extension: 'WEBP', mimeType: 'image/webp' }
    }[expectedFormat];

    if (
        typeof raw.SourceFile !== 'string' || raw.SourceFile.trim() === '' ||
        Number(raw['ExifTool:ExifToolVersion']) !== Number(scannerVersion) ||
        raw['File:FileType'] !== expected.fileType ||
        raw['File:FileTypeExtension'] !== expected.extension ||
        raw['File:MIMEType'] !== expected.mimeType
    ) {
        return false;
    }

    if (expectedFormat !== 'webp') {
        return true;
    }

    return Number.isSafeInteger(raw['RIFF:ImageWidth']) &&
        Number.isSafeInteger(raw['RIFF:ImageHeight']) &&
        raw['RIFF:ImageWidth'] === expectedDimensions.width &&
        raw['RIFF:ImageHeight'] === expectedDimensions.height;
}

function validDimensions(value) {
    return isPlainObject(value) &&
        Number.isSafeInteger(value.width) && value.width > 0 &&
        Number.isSafeInteger(value.height) && value.height > 0;
}

function isSafeMetadataPath(value) {
    return typeof value === 'string' &&
        value.trim() === value &&
        value.length > 0 &&
        value.length <= 240 &&
        !/[\u0000-\u001F\u007F]/.test(value);
}

function isPlainObject(value) {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) {
        return false;
    }
    const prototype = Object.getPrototypeOf(value);
    return prototype === Object.prototype || prototype === null;
}
